apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ttt
  template:
    metadata:
      labels:
        app: ttt
    spec:
      containers:
      - image: jspitman/ttt-nginx
        name: ttt
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        args:
        - /ttt-entrypoint.sh averylongparameter1 averylongparameter2 averylongparameter3
          averylongparameter4 averylongparameter5 averylongparameter6
