kind: Role
apiVersion: authorization.openshift.io/v1
metadata:
  name: example-role
rules:
- apiGroups: [""]
  attributeRestrictions: null
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: example-rolebinding
subjects:
- kind: User
  name: example-user
roleRef:
  name: example-role
