kind: Role
apiVersion: authorization.openshift.io/v1
metadata:
  name: example-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: example-rolebinding
subjects:
- kind: User
  name: example-user
roleRef:
  kind: Role
  name: example-role
